import { ethers } from "ethers";

// contractConfig.json is auto-generated by scripts/deploy.js
// If it doesn't exist yet, a placeholder is used so the app still loads.
let contractAddress = "";
let contractABI = [];

try {
  const config = await import("./contractConfig.json");
  contractAddress = config.address || "";
  contractABI = config.abi || [];
} catch {
  console.warn(
    "[contract.js] contractConfig.json not found. Deploy the contract first with:\n" +
      "  npx hardhat run scripts/deploy.js --network amoy"
  );
}

export { contractAddress, contractABI };

/**
 * Returns an ethers BrowserProvider backed by MetaMask.
 * @throws if MetaMask is not installed
 */
export function getProvider() {
  if (!window.ethereum) {
    throw new Error(
      "MetaMask not detected. Please install MetaMask from https://metamask.io"
    );
  }
  return new ethers.BrowserProvider(window.ethereum);
}

/**
 * Returns the active signer from MetaMask.
 * Triggers a wallet connection request if not already connected.
 */
export async function getSigner() {
  const provider = getProvider();
  return await provider.getSigner();
}

/**
 * Returns a Contract instance connected to BlockCertSBT.
 * @param {ethers.Signer | ethers.Provider} signerOrProvider
 */
export function getContract(signerOrProvider) {
  if (!contractAddress) {
    throw new Error(
      "Contract address not configured. Deploy the contract and restart the frontend."
    );
  }
  if (!contractABI || contractABI.length === 0) {
    throw new Error(
      "Contract ABI not configured. Deploy the contract and restart the frontend."
    );
  }
  return new ethers.Contract(contractAddress, contractABI, signerOrProvider);
}

/**
 * Truncates an Ethereum address to the format 0x1234...5678
 * @param {string} address - Full 42-char Ethereum address
 * @returns {string} Truncated address
 */
export function formatAddress(address) {
  if (!address || address.length < 10) return address || "";
  return `${address.slice(0, 6)}...${address.slice(-4)}`;
}

/**
 * Requests MetaMask to switch to Polygon Amoy testnet (chainId 80002).
 * Adds the network if it doesn't exist in the wallet yet.
 */
export async function switchToAmoy() {
  if (!window.ethereum) throw new Error("MetaMask not detected");

  try {
    await window.ethereum.request({
      method: "wallet_switchEthereumChain",
      params: [{ chainId: "0x13882" }], // 80002 in hex
    });
  } catch (switchError) {
    // Error code 4902 = chain not added to MetaMask
    if (switchError.code === 4902) {
      await window.ethereum.request({
        method: "wallet_addEthereumChain",
        params: [
          {
            chainId: "0x13882",
            chainName: "Polygon Amoy Testnet",
            nativeCurrency: { name: "MATIC", symbol: "MATIC", decimals: 18 },
            rpcUrls: ["https://rpc-amoy.polygon.technology/"],
            blockExplorerUrls: ["https://amoy.polygonscan.com/"],
          },
        ],
      });
    } else {
      throw switchError;
    }
  }
}

/**
 * Requests MetaMask to switch to Hardhat Localhost (chainId 31337).
 */
export async function switchToHardhat() {
  if (!window.ethereum) throw new Error("MetaMask not detected");

  try {
    await window.ethereum.request({
      method: "wallet_switchEthereumChain",
      params: [{ chainId: "0x7a69" }], // 31337 in hex
    });
  } catch (switchError) {
    if (switchError.code === 4902) {
      await window.ethereum.request({
        method: "wallet_addEthereumChain",
        params: [
          {
            chainId: "0x7a69",
            chainName: "Hardhat Localhost",
            nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
            rpcUrls: ["http://127.0.0.1:8545"],
          },
        ],
      });
    } else {
      throw switchError;
    }
  }
}
